Improve api
IT-REX-Platform/flashcard_service pull request #23
Opened 2023-08-12 16:55 UTC by myluki2000

## Description of changes
* Improves the API by moving mutations into their own type
* Generally improves the codebase of the service
* More thorough automated tests

  
## How has this been tested?

Please describe the test strategy you followed. If not tested, please explain why.

- [x] automated unit test
- [ ] automated integration test
- [ ] manual, exploratory test
    
## Checklist before requesting a review

- [ ] My code is easy to understand
- [ ] My code follows the [coding guidelines](https://github.com/IT-REX-Platform/wiki/blob/main/dev-manuals/backend/coding-guidelines.md) of this project
- [ ] My code fulfills all acceptance criteria
- [ ] The test coverage (line and branch) is reasonably high, especially on Service classes and other classes with complex logic
- [ ] I have made corresponding changes to the documentation or
  the [wiki/adr](https://github.com/IT-REX-Platform/wiki/tree/main/adr)
- [ ] I made no breaking changes in the database schema or if so, I will perform a database migration

## Checklist for reviewer

- The code is easy to understand
- The code follows
  the [coding guidelines](https://github.com/IT-REX-Platform/wiki/blob/main/dev-manuals/backend/coding-guidelines.md) of
  this project
- The code is tested or if not, the reason is documented or discussed
- The added and existing tests reasonably cover the code change
- The code has no breaking changes in the database schema or if so, the assignee is aware of it and
  will perform a database migration

2023-08-13 13:47 UTC, myluki2000 commented
DB migration might be a bit more complicated on this one, depending on how exactly hibernate constructs its relationships depending on how you declare your Entities.

Is deleting the whole flashcard DB a valid migration strategy? 😓

2023-08-14 12:15 UTC, PaulBredl commented
> DB migration might be a bit more complicated on this one, depending on how exactly hibernate constructs relationships between Entities depending on how you declare your Entity classes in Java.
> 
> Is deleting the whole flashcard DB a valid migration strategy? 😅

In this case I would say yes

2023-08-14 12:18 UTC, PaulBredl commented on src/main/resources/graphql/query.graphqls
>      flashcardSetsByAssessmentIds(assessmentIds: [UUID!]!): [FlashcardSet!]!
wir brauchen auch irgendwann ne non throwing query

2023-08-14 12:19 UTC, PaulBredl commented on src/test/java/de/unistuttgart/iste/gits/flashcard_service/api/MutationDeleteFlashcardSetTest.java
> +    @Transactional
Bitte mit @Commit. Sonst macht Spring nichts in der Datenbank und man findet keine DB Fehler wie constraint violations

2023-08-14 12:20 UTC, PaulBredl commented on src/test/java/de/unistuttgart/iste/gits/flashcard_service/api/MutationDeleteFlashcardSetTest.java
> +    @Transactional
Bei Tests, die Fehler erwarten allerdings ist das so richtig (@Commit würde hier einen Fehlschlag liefern, weil es ja keinen Commit in der DB gab)

2023-08-14 12:22 UTC, PaulBredl commented on src/test/java/de/unistuttgart/iste/gits/flashcard_service/test_utils/TestUtils.java
> +    public List<FlashcardSetEntity> populateFlashcardSetRepository(FlashcardSetRepository repo) {
Interesting way to create test data. I personally prefer builders, but this works too 👍

2023-08-14 12:23 UTC, PaulBredl requested changes
minor issue

2023-08-14 12:23 UTC, PaulBredl commented on src/main/resources/graphql/query.graphqls
>      flashcardSetsByAssessmentIds(assessmentIds: [UUID!]!): [FlashcardSet!]!
(aber nicht jetzt)

2023-08-14 12:38 UTC, myluki2000 commented on src/test/java/de/unistuttgart/iste/gits/flashcard_service/api/MutationDeleteFlashcardSetTest.java
> +    @Transactional
Ah da hab ich die @Commit annotation falsch verstanden. Hab gedacht die ist dafür da wenn man will dass die Daten von dem Test in die DB geschrieben werden sodass sie dann in einem anderen Test noch da sind

das ist dann in anderen services aber glaub auch oft falsch. müsste man sich mal anschauen

2023-08-14 12:45 UTC, PaulBredl commented on src/test/java/de/unistuttgart/iste/gits/flashcard_service/api/MutationDeleteFlashcardSetTest.java
> +    @Transactional
ja kann sein. Aber ist auch kein Weltuntergang in den meisten Fällen

2023-08-14 12:46 UTC, PaulBredl approved these changes

2023-08-14 12:47 UTC, merged